#!/bin/bash
#
#   algorand - run algorand on a worker node
#
#   Assume algorand is installed on the current environment under the path
#   "$HOME/install/algorand" and deployed under the path
#   "$HOME/deploy/algorand".
#
#   Depending on the worker role defined during deployment, start or stop an
#   algorand full or client node or both.
#

set -e

script_name='algorand'
install_root="${HOME}/install/algorand"
deploy_root="${HOME}/deploy/algorand"

node_root="${deploy_root}/n"
client_root="${deploy_root}/c"


# Utility functions - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

fatal() {
    local msg="$1" ; shift

    exec >&2

    echo "${script_name}: ${msg}"
    echo
    echo "Usage: $0 start (1)"
    echo "       $0 stop (2)"
    echo
    echo "Either start (1) or stop (2) the full and client nodes deployed on"
    echo "this worker"

    exit 1
}

setup_environment() {
    if [ ! -e "${install_root}" ] ; then
	fatal "cannot find algorand install at '${install_root}'"
    fi

    export PATH="${install_root}/go/bin:${PATH}"

    if ! command -v 'goal' > '/dev/null' 2> '/dev/null' ; then
	fatal "cannot find goal executable in '${install_root}'"
    fi
}


# Actions - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

start() {
    local dirs dir

    dirs=("${deploy_root}/n"*)
    if [ $# -gt 0 ] ; then
		dirs=("${@/#/${deploy_root}/n}")
    fi

    for dir in "${dirs[@]}" ; do
	if [ -e "${dir}" ] ; then
	    "${dir}/start" >> "${dir}/out" 2>> "${dir}/err"
	fi
    done
}

stop() {
    local dirs dir

    dirs=("${deploy_root}/n"*)
    if [ $# -gt 0 ] ; then
		dirs=("${@/#/${deploy_root}/n}")
    fi

    for dir in "${dirs[@]}" ; do
	if [ -e "${dir}" ] ; then
	    goal node stop --datadir "${dir}" > '/dev/null' || true
	fi
    done

    for dir in "${dirs[@]}" ; do
	if [ -e "${dir}" ] ; then
	    killall 'algod' 2> '/dev/null' || true

        rm -rf "${HOME}/.algorand"

        break
	fi
    done
}

die() {
    local dirs

    dirs=("${deploy_root}/n"*)
    if [ $# -gt 0 ] ; then
		dirs=("${@/#/${deploy_root}/n}")
    fi

    for dir in "${dirs[@]}" ; do
	if [ -e "${dir}" ] ; then
        killall -KILL 'algod' 2> '/dev/null' || true

        break
    fi
    done
}


# Main script - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

setup_environment

if [ $# -lt 1 ] ; then
    fatal "missing action operand"
fi

action="$1" ; shift

case "${action}" in
    'kill')
	die "$@"
	;;
    'start')
	start "$@"
	;;
    'stop')
	stop "$@"
	;;
    *)
	fatal "unknown action: '${action}'"
	;;
esac
