#!/usr/bin/env bash

set -e

script_name='solana'
install_root="${HOME}/install/solana"
deploy_root="${HOME}/deploy/solana"


# Utility functions - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

fatal() {
    local msg="$1" ; shift

    exec >&2

    echo "${script_name}: ${msg}"
    echo
    echo "Usage: $0 start (1)"
    echo "       $0 stop (2)"
    echo "       $0 kill (3)"
    echo
    echo "Either start (1), gracefully stop (2) or kill (3) the nodes deployed"
    echo "on this worker"

    exit 1
}

setup_environment() {
    if [ ! -e "${install_root}" ] ; then
	fatal "cannot find solana install at '${install_root}'"
    fi

    export PATH="${install_root}/bin:${PATH}"

    if ! command -v 'agave-validator' > '/dev/null' 2> '/dev/null' ; then
	fatal "cannot find agave-validator executable in '${install_root}'"
    fi

	export RUST_LOG="solana_metrics=warn,debug"
	export RUST_BACKTRACE=full
	# export RUST_LOG="info"
}

waitForNodeToInit() {
	local initCompleteFile="$1" ; shift
    local waitTime="$1" ; shift

	echo "--- waiting for $initCompleteFile"
	declare startTime=$SECONDS
	while [[ ! -r $initCompleteFile ]]; do
	declare timeWaited=$((SECONDS - startTime))
	if [[ $timeWaited -ge $waitTime ]]; then
		echo "^^^ +++"
		echo "Error: $initCompleteFile not found in $timeWaited seconds"
		nkill
		exit 1
	fi
	echo "Waiting for $initCompleteFile ($timeWaited)..."
	sleep 5
	done
	echo "$initCompleteFile detected"
}


# Actions - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

start() {
    local dirs dir configdir pid rpcport gossipport dynamicport addr bootstrapaddr bootstrapgossipport status_code

	dirs=("${deploy_root}/n"*)
    if [ $# -gt 0 ] ; then
		dirs=("${@/#/${deploy_root}/n}")
    fi

    for dir in "${dirs[@]}" ; do
	if [ -d "${dir}" ] ; then
		configdir="${dir}/config"
	    rpcport="$(cat "${configdir}/rpcport")"
	    gossipport="$(cat "${configdir}/gossipport")"
	    dynamicport="$(cat "${configdir}/dynamicport")"

	    if ! echo "${rpcport}" | grep -Pq '^\d+$' ; then
		fatal "cannot find rpc port in '${configdir}/rpcport'"
	    fi

	    if ! echo "${gossipport}" | grep -Pq '^\d+$' ; then
		fatal "cannot find gossip port in '${configdir}/gossipport'"
	    fi

	    if ! echo "${dynamicport}" | grep -Pq '^\d+$' ; then
		fatal "cannot find dynamic port in '${configdir}/dynamicport'"
	    fi

		for attempt in {1..10}
		do
			if [ -d "${configdir}/bootstrap-validator" ] ; then
			addr="$(cat "${configdir}/addr")"
			# "${dir}"/multinode-demo/bootstrap-validator.sh \
			#  --gossip-host ${addr} \
			#  --gossip-port ${gossipport} \
			#  --dynamic-port-range "${dynamicport}-$(( dynamicport + 14 ))" \
			#  --init-complete-file "${dir}/init-complete-node.log" \
			#  --wait-for-supermajority 1 \
			#  --expected-bank-hash "$(cat "${configdir}/bank-hash")" \
			#  --enable-rpc-transaction-history \
			#  --rpc-faucet-address 127.0.0.1:9900 \
			# --no-duplicate-instance-check \
			agave-validator \
			--gossip-host ${addr} \
			--gossip-port ${gossipport} \
			--dynamic-port-range "${dynamicport}-$(( dynamicport + 14 ))" \
			--init-complete-file "${dir}/init-complete-node.log" \
			--wait-for-supermajority 1 \
			--expected-bank-hash "$(cat "${configdir}/bank-hash")" \
			--enable-rpc-transaction-history \
			--require-tower \
			--ledger "${configdir}/bootstrap-validator" \
			--rpc-port ${rpcport} \
			--snapshot-interval-slots 200 \
			--no-incremental-snapshots \
			--identity "${configdir}/bootstrap-validator/identity.json" \
			--vote-account "${configdir}/bootstrap-validator/vote-account.json" \
			--no-poh-speed-test \
			--no-os-network-limits-test \
			--no-wait-for-vote-to-start-leader \
			--full-rpc-api \
			--allow-private-addr \
			--log - \
			>> "${dir}/out" 2>> "${dir}/err" &
			else
			bootstrapaddr="$(cat "${configdir}/bootstrapaddr")"
			bootstrapgossipport="$(cat "${configdir}/bootstrapgossipport")"

			if ! echo "${bootstrapgossipport}" | grep -Pq '^\d+$' ; then
			fatal "cannot find bootstrap gossip port in '${configdir}/bootstrapgossipport'"
			fi

			# export SKIP_ACCOUNTS_CREATION=1/
			# "${dir}"/multinode-demo/validator.sh \
			#  --entrypoint "${bootstrapaddr}:${bootstrapgossipport}" \
			#  --gossip-port ${gossipport} \
			#  --rpc-port ${rpcport} \
			#  --dynamic-port-range "${dynamicport}-$(( dynamicport + 14 ))" \
			#  --expected-shred-version "$(cat "${configdir}/shred-version")" \
			#  --identity "${configdir}/identity.json" \
			#  --vote-account "${configdir}/vote-account.json" \
			#  --no-airdrop \
			#  --expected-bank-hash "$(cat "${configdir}/bank-hash")" \
			#  --init-complete-file "${dir}/init-complete-node.log" \
			#  --wait-for-supermajority 1 \
			#  --enable-rpc-transaction-history \
			for gossip_attempt in {1..10}
			do
				solana-gossip \
				--allow-private-addr \
				rpc-url \
				--timeout 180 \
				--entrypoint "${bootstrapaddr}:${bootstrapgossipport}" || status_code=$?

				if [ -z "${status_code}" ]
				then
					break
				else
					sleep 5
				fi
			done



			# --no-duplicate-instance-check \
			agave-validator \
			--max-genesis-archive-unpacked-size 1073741824 \
			--no-poh-speed-test \
			--no-os-network-limits-test \
			--entrypoint "${bootstrapaddr}:${bootstrapgossipport}" \
			--gossip-port ${gossipport} \
			--rpc-port ${rpcport} \
			--dynamic-port-range "${dynamicport}-$(( dynamicport + 14 ))" \
			--expected-shred-version "$(cat "${configdir}/shred-version")" \
			--identity "${configdir}/identity.json" \
			--vote-account  "${configdir}/vote-account.json" \
			--expected-bank-hash "$(cat "${configdir}/bank-hash")" \
			--init-complete-file "${dir}/init-complete-node.log" \
			--wait-for-supermajority 1 \
			--enable-rpc-transaction-history \
			--ledger "${configdir}/validator" \
			--log - \
			--full-rpc-api \
			--no-incremental-snapshots \
			--allow-private-addr \
			--require-tower \
			>> "${dir}/out" 2>> "${dir}/err" &
			fi
			pid=$!

			if [ -d "${configdir}/bootstrap-validator" ] ; then
				sleep 2
			else
				sleep 10
			fi

			if [[ -z $pid ]] || ! kill -0 "$pid"; then
				echo "############## validator exited, restarting ##############"
				continue
			else
				echo ${pid} > "${dir}/pid"
				break
			fi
		done
	fi
    done

	for dir in "${dirs[@]}" ; do
	if [ -d "${dir}" ] ; then
		waitForNodeToInit "${dir}/init-complete-node.log" 200
	fi
	done

    sleep 2
}

_kill() {
    local sig="$1" ; shift
    local dirs dir pid dead configdir rpcport gossipport

    dirs=("${deploy_root}/n"*)
    if [ $# -gt 0 ] ; then
		dirs=("${@/#/${deploy_root}/n}")
    fi

    for dir in "${dirs[@]}" ; do
	if [ ! -d "${dir}" ] ; then
	    continue
	elif [ ! -f "${dir}/pid" ] ; then
	    continue
	fi

	# configdir="${dir}/config"
	# rpcport="$(cat "${configdir}/rpcport")"
	# gossipport="$(cat "${configdir}/gossipport")"
	pid="$(cat "${dir}/pid")"

	if echo "${pid}" | grep -Pq '^\d+$' ; then
	    kill "${sig}" ${pid} 2> '/dev/null' || true
		# fuser -k "${sig}" "${rpcport}/tcp" 2> '/dev/null' || true
		# fuser -k "${sig}" "${gossipport}/tcp" 2> '/dev/null' || true
	fi

	dead=0
	for i in $(seq 1 5) ; do
	    if ! ps ${pid} > '/dev/null' ; then
		dead=1
		break
	    fi

	    sleep 1
	done

	if [ ${dead} -eq 0 ] ; then
	    kill -KILL ${pid} 2> '/dev/null' || true
	fi

	rm "${dir}/pid"
	rm "${dir}/init-complete-node.log" 2> '/dev/null' || true
    done
}

stop() {
    _kill -INT "$@"
}

nkill() {
    _kill -KILL "$@"
}

term() {
	_kill -TERM "$@"
}

segv() {
	_kill -SEGV "$@"
}


# Main script - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

setup_environment

if [ $# -lt 1 ] ; then
    fatal "missing action operand"
fi

action="$1" ; shift

case "${action}" in
    'kill')
	nkill "$@"
	;;
    'start')
	start "$@"
	;;
    'stop')
	stop "$@"
	;;
    'term')
	term "$@"
	;;
    'segv')
	segv "$@"
	;;
    *)
	fatal "unknown action: '${action}'"
	;;
esac
