#!/bin/bash
#
#   build-algorand - build the Algorand blockchain from its repository
#

set -e

# Create an install dir if not already there.
#
if [ ! -e 'install' ] ; then
    mkdir 'install'
fi

if [ -e 'install/algorand' ] ; then
    sudo rm -rf 'install/algorand'
fi

golang_version='1.20.7'

algorand_url='https://github.com/algorand/go-algorand.git'
algorand_checkout='v3.22.0-stable'

if [ ! -f "$HOME/helper" ]; then
    echo "Cannot find helper script" >&2
    exit 1
fi
. "$HOME/helper"

# Install common utilities.
#
sudo -n apt-get -o DPkg::Lock::Timeout=1200 install -yy 'python3-pip'
asdf_install golang "$golang_version"

# Clone Algorand from the official repository and build it.
#
mkdir 'install/algorand'
(
    cd 'install/algorand'

	git init
	git remote add origin "${algorand_url}"
	git fetch --depth 1 origin "${algorand_checkout}"
	git checkout FETCH_HEAD

    # For some obscure reason, Algorand does not build properly if the GOPATH
    # is not $HOME (do these people make package with their ass?).
    # Build with GOPATH="$HOME" then move "$HOME/go" in the repository.
    #
    # export GOPATH="${PWD}/go"

    sudo --non-interactive --preserve-env='PATH' \
	 ./scripts/configure_dev.sh

    make build

    # Fix the Golang/Algorand devs stupidity.
    #
    # mv "${HOME}/go" './go'

    # export GOPATH="${PWD}/go"

	GOPATHBIN=${GOPATH%%:*}/bin

	mkdir -p ./go/bin
	for bin in algod goal kmd
	do
		cp ${GOPATHBIN}/${bin} ./go/bin
	done
    tar czfv '../algorand.tar.gz' --transform 's,^,algorand/,' go/bin/algod go/bin/goal go/bin/kmd

    # Install pyteal for smart contract compilation
    #
    pip3 install pyteal
)

mkdir 'install/algorand/algorand-tools'
(
    cd 'install/algorand/algorand-tools'

    cat > 'main.go' <<'EOF'
package main

import (
	"bufio"
	"context"
	"crypto/sha512"
	"database/sql"
	"encoding/base32"
	"fmt"
	"os"
	"strconv"

	"github.com/algorand/go-algorand-sdk/v2/mnemonic"
	"github.com/algorand/go-algorand/logging"
	"github.com/algorand/go-algorand/protocol"
	"github.com/algorand/go-algorand/util/db"
	"github.com/algorand/msgp/msgp"
)

/* Classical signatures */
type ed25519PublicKey [32]byte
type ed25519PrivateKey [64]byte

// PrivateKey is an exported ed25519PrivateKey
type PrivateKey ed25519PrivateKey

// PublicKey is an exported ed25519PublicKey
type PublicKey ed25519PublicKey

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PublicKey) UnmarshalMsgWithState(bts []byte, st msgp.UnmarshalState) (o []byte, err error) {
	if st.AllowableDepth == 0 {
			err = msgp.ErrMaxDepthExceeded{}
			return
	}
	st.AllowableDepth--
	bts, err = msgp.ReadExactBytes(bts, (*z)[:])
	if err != nil {
			err = msgp.WrapError(err)
			return
	}
	o = bts
	return
}

func (z *PublicKey) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithState(bts, msgp.DefaultUnmarshalState)
}
func (_ *PublicKey) CanUnmarshalMsg(z interface{}) bool {
	_, ok := (z).(*PublicKey)
	return ok
}

// A SignatureVerifier is used to identify the holder of SignatureSecrets
// and verify the authenticity of Signatures.
type SignatureVerifier = PublicKey

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SignatureSecrets) UnmarshalMsgWithState(bts []byte, st msgp.UnmarshalState) (o []byte, err error) {
	if st.AllowableDepth == 0 {
			err = msgp.ErrMaxDepthExceeded{}
			return
	}
	st.AllowableDepth--
	var field []byte
	_ = field
	var zb0003 int
	var zb0004 bool
	zb0003, zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
	if _, ok := err.(msgp.TypeError); ok {
			zb0003, zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
					err = msgp.WrapError(err)
					return
			}
			if zb0003 > 0 {
					zb0003--
					bts, err = msgp.ReadExactBytes(bts, ((*z).SignatureVerifier)[:])
					if err != nil {
							err = msgp.WrapError(err, "struct-from-array", "SignatureVerifier")
							return
					}
			}
			if zb0003 > 0 {
					zb0003--
					bts, err = msgp.ReadExactBytes(bts, ((*z).SK)[:])
					if err != nil {
							err = msgp.WrapError(err, "struct-from-array", "SK")
							return
					}
			}
			if zb0003 > 0 {
					err = msgp.ErrTooManyArrayFields(zb0003)
					if err != nil {
							err = msgp.WrapError(err, "struct-from-array")
							return
					}
			}
	} else {
			if err != nil {
					err = msgp.WrapError(err)
					return
			}
			if zb0004 {
					(*z) = SignatureSecrets{}
			}
			for zb0003 > 0 {
					zb0003--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
							err = msgp.WrapError(err)
							return
					}
					switch string(field) {
					case "SignatureVerifier":
							bts, err = msgp.ReadExactBytes(bts, ((*z).SignatureVerifier)[:])
							if err != nil {
									err = msgp.WrapError(err, "SignatureVerifier")
									return
							}
					case "SK":
							bts, err = msgp.ReadExactBytes(bts, ((*z).SK)[:])
							if err != nil {
									err = msgp.WrapError(err, "SK")
									return
							}
					default:
							err = msgp.ErrNoField(string(field))
							if err != nil {
									err = msgp.WrapError(err)
									return
							}
					}
			}
	}
	o = bts
	return
}

func (z *SignatureSecrets) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithState(bts, msgp.DefaultUnmarshalState)
}
func (_ *SignatureSecrets) CanUnmarshalMsg(z interface{}) bool {
	_, ok := (z).(*SignatureSecrets)
	return ok
}

// SignatureSecrets are used by an entity to produce unforgeable signatures over
// a message.
type SignatureSecrets struct {
	SignatureVerifier
	SK ed25519PrivateKey
}

// A Root encapsulates a set of secrets which controls some store of money.
//
// A Root is authorized to spend money and create Participations
// for which this account is the parent.
//
// It handles persistence and secure deletion of secrets.
type Root struct {
	secrets *SignatureSecrets

	store db.Accessor
}

// RestoreRoot restores a Root from a database handle.
func RestoreRoot(store db.Accessor) (acc Root, err error) {
	var raw []byte

	err = store.Atomic(func(ctx context.Context, tx *sql.Tx) error {
		var nrows int
		row := tx.QueryRow("select count(*) from RootAccount")
		err := row.Scan(&nrows)
		if err != nil {
			return fmt.Errorf("RestoreRoot: could not query storage: %v", err)
		}
		if nrows != 1 {
			logging.Base().Infof("RestoreRoot: state not found (n = %v)", nrows)
		}

		row = tx.QueryRow("select data from RootAccount")
		err = row.Scan(&raw)
		if err != nil {
			return fmt.Errorf("RestoreRoot: could not read account raw data: %v", err)
		}

		return nil
	})

	if err != nil {
		return
	}

	acc.secrets = &SignatureSecrets{}
	err = protocol.Decode(raw, acc.secrets)
	if err != nil {
		err = fmt.Errorf("RestoreRoot: error decoding account: %v", err)
		return
	}

	acc.store = store
	return
}

// Secrets returns the signing secrets associated with the Root account.
func (root Root) Secrets() *SignatureSecrets {
	return root.secrets
}

// Address returns the address associated with the Root account.
func (root Root) Address() Address {
	return Address(root.secrets.SignatureVerifier)
}

// DigestSize is the number of bytes in the preferred hash Digest used here.
const DigestSize = sha512.Size256

// Digest represents a 32-byte value holding the 256-bit Hash digest.
type Digest [DigestSize]byte

// Hash computes the SHASum512_256 hash of an array of bytes
func Hash(data []byte) Digest {
	return sha512.Sum512_256(data)
}

type (
	// Address is a unique identifier corresponding to ownership of money
	Address Digest
)

const (
	checksumLength = 4
)

var base32Encoder = base32.StdEncoding.WithPadding(base32.NoPadding)

// String returns a string representation of Address
func (addr Address) String() string {
	addrWithChecksum := make([]byte, DigestSize+checksumLength)
	copy(addrWithChecksum[:DigestSize], addr[:])
	// calling addr.GetChecksum() here takes 20ns more than just rolling it out, so we'll just repeat that code.
	shortAddressHash := Hash(addr[:])
	copy(addrWithChecksum[DigestSize:], shortAddressHash[len(shortAddressHash)-checksumLength:])
	return base32Encoder.EncodeToString(addrWithChecksum)
}

type WalletResult struct {
	Address  string
	Mnemonic string
	Error    error
}

func main() {
	netroot := os.Args[1]
	nodenum, err := strconv.ParseUint(os.Args[2], 10, 64)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	chainconfig := os.Args[3]

	file, err := os.Create(chainconfig)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	defer file.Close()

	writer := bufio.NewWriter(file)
	defer writer.Flush()

	sem := make(chan *WalletResult, nodenum)
	for i := uint64(0); i < nodenum; i++ {
		go func(i uint64) {
			result := &WalletResult{}
			filename := fmt.Sprintf("%s/wallet_%d.rootkey", netroot, i)

			rootDB, err := db.MakeAccessor(filename, true, false)
			if err != nil {
				result.Error = err
				sem <- result
				return
			}
			defer rootDB.Close()

			root, err := RestoreRoot(rootDB)
			if err != nil {
				result.Error = err
				sem <- result
				return
			}

			result.Address = root.Address().String()

			m, err := mnemonic.FromKey(root.secrets.SK[:32])
			if err != nil {
				result.Error = err
				sem <- result
				return
			}

			result.Mnemonic = m
			sem <- result
		}(i)
	}
	errs := make([]error, 0)
	for i := uint64(0); i < nodenum; i++ {
		wallet := <-sem
		if wallet.Error != nil {
			errs = append(errs, err)
			continue
		}
		fmt.Fprintf(writer, "- address:  %s\n  mnemonic: %s\n", wallet.Address, wallet.Mnemonic)
	}
	if len(errs) != 0 {
		fmt.Println(errs)
		os.Exit(1)
	}
}
EOF
    chmod 755 'main.go'

    go mod init "algorand-chainfile-generator"

	go get github.com/algorand/go-algorand-sdk/v2@5fd2c1c # v2.4.0
	go get github.com/algorand/go-algorand@7a0cd10

    go mod tidy

    go build -o algorand-chainfile-generator

    tar czfv '../../algorand-tools.tar.gz' --transform 's,^,algorand-tools/,' algorand-chainfile-generator
)
