#!/bin/bash

if [ ! -f "$HOME/.asdf/asdf.sh" ]; then
	echo "Cannot find asdf version manager" >&2
	exit 1
fi
. "$HOME/.asdf/asdf.sh"
. "$HOME/.asdf/lib/utils.bash"
. "$HOME/.asdf/plugins/direnv/lib/tools-environment-lib.bash"

run_with_plugins() {
  while [ $# -gt 0 ]; do
    if [ "--" = "$1" ]; then
      shift
      break
    fi

    local plugin version

    plugin="$1"
    shift

    if [ $# -eq 0 ]; then
      log_error "Please specify a version for $plugin."
      exit 1
    fi
    version="$1"
    shift

    # Set the appropriate ASDF_*_VERSION environment variable. This isn't
    # strictly necessary because we're not using shims, but it's nice because
    # it'll get `asdf current` to print out useful information, and if folks
    # have a special prompt configured (such as powerlevel10k), it'll know
    # about the newly activated tools.
    #
    # (this logic was copied from lib/commands/command-export-shell-version.bash)
    local upcase_name
    upcase_name=$(tr '[:lower:]-' '[:upper:]_' <<<"$plugin")
    local version_env_var="ASDF_${upcase_name}_VERSION"
    export "$version_env_var"="$version"

    _plugin_env_bash "$plugin" "$version" "$plugin $version not installed. Run 'asdf install $plugin $version' and try again."
  done
}


asdf_install() {
	local name="$1"
	local version="$2"
	asdf plugin add "$name"
	asdf install "$name" "$version"
	eval "$(run_with_plugins "$name" "$version")"
}

if ! command -v 'sudo' > '/dev/null' ; then
	echo "Cannot find command 'sudo'" >&2
	exit 1
fi

while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 ; do
	echo 'Waiting for release of dpkg/apt locks'
	sleep 5
done
