#!/bin/bash
#
#   install-quorum - install the Quorum blockchain from its repository
#

set -e

golang_url="https://go.dev/dl/go1.16.15.linux-$(dpkg --print-architecture).tar.gz"

quorum_url='https://github.com/Consensys/quorum.git'
quorum_checkout='919800f019cc5d2b931b5cd81600640a8e7cd444'

istanbul_url='https://github.com/ConsenSys/istanbul-tools.git'
istanbul_checkout='master'

if ! command -v 'sudo' > '/dev/null' ; then
    echo "Cannot find command 'sudo'" >&2
    exit 1
fi

# Install common utilities as well as golang.
#
sudo -n apt-get install -yy 'git' 'make'

# Create an install dir if not already there.
#
if [ ! -e 'install' ] ; then
    mkdir 'install'
fi

curl -L "${golang_url}" | tar --one-top-level='install/go1.16.15' --strip-components=1 -xzf -
export PATH="${PWD}/install/go1.16.15/bin:${PATH}"

# Clone Quorum from the official repository and build it.
#
git clone "${quorum_url}" 'install/quorum'
(
    cd 'install/quorum'

    git checkout "${quorum_checkout}"

    # Avoid modification outside of this repository.
    # This is important because some other installed software could use
    # different versions of Go.
    #
    export GOPATH="${PWD}/go"

    make all

	sudo find . -not \( -path './build/bin/bootnode' -or -path './build/bin/evm' -or -path './build/bin/geth' -or -path './build/bin/puppeth' \) -delete || true
)

# Clone Quorum Istanbul tools from the official repository and build them.
#
git clone "${istanbul_url}" 'install/quorum/istanbul-tools'
(
    cd 'install/quorum/istanbul-tools'

    git checkout "${istanbul_checkout}"

    # Avoid modification outside of this repository.
    # This is important because some other installed software could use
    # different versions of Go.
    #
    export GOPATH="${PWD}/../go"

    make

	sudo find . -not -path './build/bin/istanbul' -delete || true
)

sudo rm -rf "${HOME}/install/go1.16.15"
